openapi: 3.0.0
info:
  title: Calculator
  description: Just calculator API
  version: '1.0'
servers:
  - url: http://localhost:3000
paths:
  /calc:
    post:
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/calcResult'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
      requestBody:
        required: true
        description: Optional description in *Markdown*
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calculatorOperation'
      parameters:
        - name: op
          in: header
          description: The Operation
          required: true
          explode: true
          schema:
            $ref: '#/components/schemas/OperationType'
  /auth:
    post:
      responses:
        '201':
          description: You are logged in
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/authResult'
        '400':
          $ref: '#/components/responses/ValidationError'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/authBody'
components:
  schemas:
    calculatorOperation:
      type: object
      required:
        - num1
        - num2
      properties:
        num1:
          type: number
          format: float
        num2:
          type: number
          format: float
    authBody:
      type: object
      required:
        - email
      properties:
        email:
          type: string
    calcResult:
      type: object
      properties:
        result:
          type: number
          format: float
    authResult:
      type: object
      properties:
        message:
          type: string
        token:
          type: string
    OperationType:
      title: OperationType
      enum:
        - add
        - sub
        - multiply
        - div
        - pow
      type: string
      description: Possible operators are sum, subtract, multiply, divide, pow
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Not authorized
    ValidationError:
      description: Invalid request parameters
tags:
  - name: Simple Calculator
    description: ''
security:
  - bearerAuth: []
